version: "3.9"

services:
  # --- development container ---
  dev:
    image: node:20-bookworm
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"   # Vite
    ports:
      - "5173:5173"                                         # hot‑reload
    volumes:
      - ./:/app                                            # mount kode lokal
      - /app/node_modules                                  # hindari rewrite host
    environment:
      - TZ=Asia/Jakarta

  # --- production container (optional, untuk tes lokal) ---
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - dev       # hanya kalau ingin memastikan dev selesai build dulu
    environment:
      - TZ=Asia/Jakarta
